### ISSUE TITLE
TimeoutError

### ISSUE THREAD

**Issue by NeotenicPrimate** [graphistry/pygraphistry#303] opened 2022-01-26 20:36 UTC
When I try to register, like so:

```python
import graphistry

graphistry.register(api=3, 
                    protocol="https", 
                    server="hub.graphistry.com", 
                    username="my_username", 
                    password="my_password")
```

I get timed out, and it returns the following error message.

```
---------------------------------------------------------------------------
TimeoutError                              Traceback (most recent call last)
/usr/local/lib/python3.9/site-packages/urllib3/connection.py in _new_conn(self)
    173         try:
--> 174             conn = connection.create_connection(
    175                 (self._dns_host, self.port), self.timeout, **extra_kw

/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py in create_connection(address, timeout, source_address, socket_options)
     95     if err is not None:
---> 96         raise err
     97 

/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py in create_connection(address, timeout, source_address, socket_options)
     85                 sock.bind(source_address)
---> 86             sock.connect(sa)
     87             return sock

TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

NewConnectionError                        Traceback (most recent call last)
/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    698             # Make the request on the httplib connection object.
--> 699             httplib_response = self._make_request(
    700                 conn,

/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py in _make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
    381         try:
--> 382             self._validate_conn(conn)
    383         except (SocketTimeout, BaseSSLError) as e:

/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py in _validate_conn(self, conn)
   1009         if not getattr(conn, "sock", None):  # AppEngine might not have  `.sock`
-> 1010             conn.connect()
   1011 

/usr/local/lib/python3.9/site-packages/urllib3/connection.py in connect(self)
    357         # Add certificate verification
--> 358         conn = self._new_conn()
    359         hostname = self.host

/usr/local/lib/python3.9/site-packages/urllib3/connection.py in _new_conn(self)
    185         except SocketError as e:
--> 186             raise NewConnectionError(
    187                 self, "Failed to establish a new connection: %s" % e

NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x15cb5adf0>: Failed to establish a new connection: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

MaxRetryError                             Traceback (most recent call last)
/usr/local/lib/python3.9/site-packages/requests/adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    438             if not chunked:
--> 439                 resp = conn.urlopen(
    440                     method=request.method,

/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    754 
--> 755             retries = retries.increment(
    756                 method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]

/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py in increment(self, method, url, response, error, _pool, _stacktrace)
    573         if new_retry.is_exhausted():
--> 574             raise MaxRetryError(_pool, url, error or ResponseError(cause))
    575 

MaxRetryError: HTTPSConnectionPool(host='hub.graphistry.com', port=443): Max retries exceeded with url: /api-token-auth/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x15cb5adf0>: Failed to establish a new connection: [Errno 60] Operation timed out'))

During handling of the above exception, another exception occurred:

ConnectionError                           Traceback (most recent call last)
/var/folders/lq/47ykgyd13kn3jwd84z0zkll80000gn/T/ipykernel_98907/1837756940.py in <module>
      1 import graphistry
      2 
----> 3 graphistry.register(api=3, 
      4                     protocol="https",
      5                     server="hub.graphistry.com",

/usr/local/lib/python3.9/site-packages/graphistry/pygraphistry.py in register(key, username, password, token, server, protocol, api, certificate_validation, bolt, token_refresh_ms, store_token_creds_in_memory, client_protocol_hostname)
    366         PyGraphistry.store_token_creds_in_memory(store_token_creds_in_memory)
    367         if not (username is None) and not (password is None):
--> 368             PyGraphistry.login(username, password)
    369         PyGraphistry.api_token(token or PyGraphistry._config['api_token'])
    370         PyGraphistry.authenticate()

/usr/local/lib/python3.9/site-packages/graphistry/pygraphistry.py in login(username, password, fail_silent)
    120         PyGraphistry._is_authenticated = False
    121         token = \
--> 122             ArrowUploader(
    123                 server_base_path=PyGraphistry.protocol() + '://' + PyGraphistry.server(),
    124                 certificate_validation=PyGraphistry.certificate_validation()) \

/usr/local/lib/python3.9/site-packages/graphistry/arrow_uploader.py in login(self, username, password)
    155     def login(self, username, password):
    156         base_path = self.server_base_path
--> 157         out = requests.post(
    158             f'{base_path}/api-token-auth/',
    159             verify=self.certificate_validation,

/usr/local/lib/python3.9/site-packages/requests/api.py in post(url, data, json, **kwargs)
    115     """
    116 
--> 117     return request('post', url, data=data, json=json, **kwargs)
    118 
    119 

/usr/local/lib/python3.9/site-packages/requests/api.py in request(method, url, **kwargs)
     59     # cases, and look like a memory leak in others.
     60     with sessions.Session() as session:
---> 61         return session.request(method=method, url=url, **kwargs)
     62 
     63 

/usr/local/lib/python3.9/site-packages/requests/sessions.py in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    540         }
    541         send_kwargs.update(settings)
--> 542         resp = self.send(prep, **send_kwargs)
    543 
    544         return resp

/usr/local/lib/python3.9/site-packages/requests/sessions.py in send(self, request, **kwargs)
    653 
    654         # Send the request
--> 655         r = adapter.send(request, **kwargs)
    656 
    657         # Total elapsed time of the request (approximately)

/usr/local/lib/python3.9/site-packages/requests/adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    514                 raise SSLError(e, request=request)
    515 
--> 516             raise ConnectionError(e, request=request)
    517 
    518         except ClosedPoolError as e:

ConnectionError: HTTPSConnectionPool(host='hub.graphistry.com', port=443): Max retries exceeded with url: /api-token-auth/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x15cb5adf0>: Failed to establish a new connection: [Errno 60] Operation timed out'))
```

I am on macOS.

Any help would be much appreciated.

**Comment by lmeyerov** [comment] 2022-01-26 20:45
Hi @NeotenicPrimate ! Just tested that worked here on Hub, so maybe --

* It's *not* an invalid user/pass/server thing because we'd give different errors
* can you try from a different server, in case you have firewall restrictions?
* we have rate limiting in place as a security precaution, though I doubt you'd hit that in normal circumstances
* you can also try via curl:

```bash
curl -fsv -X POST \
    -H "Content-Type: application/json" \
    -d "{\"username\": \"${GRAPHISTRY_USERNAME}\", \"password\": \"${GRAPHISTRY_PASSWORD}\"}" \
    ${GRAPHISTRY_BASE_PATH}/api-token-auth/
```

(from https://hub.graphistry.com/docs/api/2/rest/curl-tutorial/)

**Comment by NeotenicPrimate** [comment] 2022-01-26 21:44
I've tried the suggested curl command, which returns the following, even after deactivating my Firewall:

```
* Trying 77.104.152.185...
* TCP_NODELAY set
* Connection failed
* connect to 77.104.152.185 port 80 failed: Operation timed out
* Failed to connect to hub.graphistry.com port 80: Operation timed out
* Closing connection 0
```

I'm also getting a connection time out when trying to log in to the website: "This site can’t be reached hub.graphistry.com took too long to respond."

I'm guessing this too is coming from my end?

**Comment by lmeyerov** [comment] 2022-01-26 22:06
Hmm sounds like a dns issue -- hub public ip is `20.185.222.193`, & confirmed via ping:

```
lmeyerov2$ ping hub.graphistry.com
PING hub.graphistry.com (20.185.222.193): 56 data bytes
Request timeout for icmp_seq 0 # ping is disabled
```

**Comment by lmeyerov** [comment] 2022-01-26 22:08
Also, our `ttl` is 30s, so your DNS _should_ be catching any changes on our end same-minute. Mysterious!

**Comment by NeotenicPrimate** [comment] 2022-01-26 22:48
I went to campus to try it again. Now the curl command now returns:
```
*   Trying 77.104.152.185...
* TCP_NODELAY set
* Connected to hub.graphistry.com (77.104.152.185) port 80 (#0)
> POST /api-token-auth/ HTTP/1.1
> Host: hub.graphistry.com
> User-Agent: curl/7.64.1
> Accept: */*
> Content-Type: application/json
> Content-Length: 52
> 
* upload completely sent off: 52 out of 52 bytes
* Recv failure: Operation timed out
* Closing connection 0
```
But running the code in the first original post still returns the same error message.

**Comment by NeotenicPrimate** [comment] 2022-01-26 23:15
I changed absolutely nothing and it's working again! 
Thank you for taking the time to help me!

**Comment by lmeyerov** [comment] 2022-01-26 23:38
Great to hear! Closing for now :)

![image](https://user-images.githubusercontent.com/4249447/151265026-f2b2e354-8e4a-4309-a4ee-16248a667520.png)

**Closed by lmeyerov** 2022-01-26 23:38 UTC
Labels: bug
