### ISSUE TITLE
Networkx / Python3 encoding issue

### ISSUE THREAD

**Issue by lmeyerov** [graphistry/pygraphistry#48] opened 2015-12-26 00:12 UTC
From https://gist.github.com/ResidentMario/87c282ea4ebded91ee31 : 

```
import networkx as nx
import graphistry
graphistry.register(key='...[key obfuscated]...')
graph = nx.path_graph(4)
graphistry.bind(source='src', destination='dst', node='nodeid').plot(graph)```
```

Causes

```
Traceback (most recent call last):
  File "C:\Users\Alex\Anaconda3\envs\watson-graph\lib\site-packages\IPython\core\interactiveshell.py", line 3066, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-5eadd70251a7>", line 1, in <module>
    graphistry.bind(source='src', destination='dst', node='nodeid').plot(graph)
  File "C:\Users\Alex\Anaconda3\envs\watson-graph\lib\site-packages\graphistry\plotter.py", line 311, in plot
    info = PyG._etl1(dataset)
  File "C:\Users\Alex\Anaconda3\envs\watson-graph\lib\site-packages\graphistry\pygraphistry.py", line 185, in _etl1
    headers=headers, params=params)
  File "C:\Users\Alex\Anaconda3\envs\watson-graph\lib\site-packages\requests\api.py", line 107, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\Alex\Anaconda3\envs\watson-graph\lib\site-packages\requests\api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Alex\Anaconda3\envs\watson-graph\lib\site-packages\requests\sessions.py", line 454, in request
    prep = self.prepare_request(req)
  File "C:\Users\Alex\Anaconda3\envs\watson-graph\lib\site-packages\requests\sessions.py", line 388, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\Alex\Anaconda3\envs\watson-graph\lib\site-packages\requests\models.py", line 296, in prepare
    self.prepare_body(data, files, json)
  File "C:\Users\Alex\Anaconda3\envs\watson-graph\lib\site-packages\requests\models.py", line 447, in prepare_body
    body = self._encode_params(data)
  File "C:\Users\Alex\Anaconda3\envs\watson-graph\lib\site-packages\requests\models.py", line 84, in _encode_params
    return to_native_string(data)
  File "C:\Users\Alex\Anaconda3\envs\watson-graph\lib\site-packages\requests\utils.py", line 700, in to_native_string
    out = string.decode(encoding)
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8b in position 1: ordinal not in range(128)
Raw
```

When run in Python2, a graph successfully generates. I do not have a working Python3 build right now, so could not duplicate there. But, assuming the error duplicates, narrows down the scope.

**Comment by ResidentMario** [comment] 2015-12-26 00:27
Converting to a dataframe was the suggested solution but I'm still getting the same error after doing so:

https://gist.github.com/ResidentMario/afb92d96beb222854e51

**Comment by lmeyerov** [comment] 2016-01-17 09:45
Slowly getting better. Interim, I marked Python 3 in the README.md as experimental.

**Comment by thibaudh** [comment] 2016-02-09 01:20
Tested with Python 2 and 3 using api 1 and 2. Cannot reproduce. Closing, but feel free to reopen.

**Closed by thibaudh** 2016-02-09 01:20 UTC
Labels: bug, p1
